#!/bin/sh

mkdir -p docs
cd ..
ls ChasingBottoms/*hs | grep -v '/IsType.hs$' | \
  xargs haddock -h -oChasingBottoms/docs
tar zcvf ChasingBottoms/chasing-bottoms.tar.gz ChasingBottoms/*hs ChasingBottoms/docs/*
