#!/bin/sh

mkdir -p docs && \
cd .. && \
ls ChasingBottoms.hs ChasingBottoms/*hs | grep -v '/IsType.hs$' | \
  xargs haddock -h --title="Chasing Bottoms" --prologue=ChasingBottoms/Header \
  -oChasingBottoms/docs \
  && \
rm -rf chasing-bottoms && \
mkdir -p chasing-bottoms && \
cp -p ChasingBottoms/LICENSE chasing-bottoms && \
( ls -d ChasingBottoms.hs ChasingBottoms/*hs | \
  xargs -n 1 -i rsync -arR {} chasing-bottoms ) && \
rsync -ar ChasingBottoms/docs chasing-bottoms && \
tar zcvf ChasingBottoms/chasing-bottoms.tar.gz chasing-bottoms
